language: node_js
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile@1
install:
  - npm ci || npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
  - npm run build
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run cover
